sudo: required
services:
  - docker
before_install:
  - docker build -t avakumov/react-docker -f Dockerfile.dev .
scripts:
  - docker run -e CI=true avakumov/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-912005163095"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"